Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 103, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\qsystem\urls.py", line 17, in <module>
    url(r'^accounts/', include('accounts.urls')),
  File "c:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "c:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\urls.py", line 2, in <module>
    from accounts import views
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\views.py", line 39
    
    ^
IndentationError: expected an indented block
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 103, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\qsystem\urls.py", line 17, in <module>
    url(r'^accounts/', include('accounts.urls')),
  File "c:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "c:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\urls.py", line 2, in <module>
    from accounts import views
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\views.py", line 3, in <module>
    from accounts.models import User, UserForm
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\models.py", line 3
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 103, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\qsystem\urls.py", line 17, in <module>
    url(r'^accounts/', include('accounts.urls')),
  File "c:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "c:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\urls.py", line 7, in <module>
    url(r'^login/$', vies.login, name = 'login'),
NameError: name 'vies' is not defined
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 103, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\qsystem\urls.py", line 17, in <module>
    url(r'^accounts/', include('accounts.urls')),
  File "c:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "c:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\urls.py", line 8, in <module>
    url(r'^login/submit/$', vies.login_submit, name = 'login'),
NameError: name 'vies' is not defined
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 103, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\qsystem\urls.py", line 17, in <module>
    url(r'^accounts/', include('accounts.urls')),
  File "c:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "c:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\urls.py", line 8, in <module>
    url(r'^login/submit/$', vies.login_submit, name = 'login'),
NameError: name 'vies' is not defined
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 103, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\Python27\lib\site-packages\django\core\urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "c:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\qsystem\urls.py", line 17, in <module>
    url(r'^accounts/', include('accounts.urls')),
  File "c:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "c:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\urls.py", line 8, in <module>
    url(r'^login/submit/$', vies.login_submit, name = 'login'),
NameError: name 'vies' is not defined
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\views.py", line 11, in register
    return render(request, 'accounts/register.html', {"error_msg":error_msg, "is_error":is_error})
  File "c:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: accounts/register.html
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\views.py", line 11, in register
    return render(request, 'accounts/register.html', {"error_msg":error_msg, "is_error":is_error})
  File "c:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: accounts/register.html
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\views.py", line 11, in register
    return render(request, 'accounts/register.html', {"error_msg":error_msg, "is_error":is_error})
  File "c:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: accounts/register.html
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\views.py", line 11, in register
    return render(request, 'accounts/register.html', {"error_msg":error_msg, "is_error":is_error})
  File "c:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: accounts/register.html
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\views.py", line 11, in register
    return render(request, 'accounts/register.html', {"error_msg":error_msg, "is_error":is_error})
  File "c:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: accounts/register.html
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\views.py", line 11, in register
    return render(request, 'accounts/register.html', {"error_msg":error_msg, "is_error":is_error})
  File "c:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: accounts/register.html
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\views.py", line 11, in register
    return render(request, 'accounts/register.html', {"error_msg":error_msg, "is_error":is_error})
  File "c:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: accounts/register.html
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\views.py", line 11, in register
    return render(request, 'accounts/register.html', {"error_msg":error_msg, "is_error":is_error})
  File "c:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: accounts/register.html
Not Found: /accounts/register/submit/
Not Found: /favicon.ico
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\views.py", line 11, in register
    return render(request, 'accounts/register.html', {"error_msg":error_msg, "is_error":is_error})
  File "c:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: accounts/register.html
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\django\core\handlers\base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "d:\GitHub\Online-questionnaire-survey-system\qsystem\accounts\views.py", line 11, in register
    return render(request, 'accounts/register.html', {"error_msg":error_msg, "is_error":is_error})
  File "c:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "c:\Python27\lib\site-packages\django\template\loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: accounts/register.html
